name: Secrets and Environment Variables

on: workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
